# Generated by Django 4.1.3 on 2022-11-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_simple', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stripe_price_id',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
    ]
