# Generated by Django 4.1.3 on 2022-11-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_simple', '0002_item_stripe_price_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='stripe_price_id',
            field=models.CharField(max_length=200),
        ),
    ]
